### ISSUE TITLE
RTI Connext  DDS Connectivity Framework for DDS Blockset

### ISSUE THREAD

**Issue by saeed-NA** [rticommunity/rticonnextdds-simulink-ddsblockset#1]
The link provided for downloading in Matlab add-on is not valid

**Comment by angelrti** [comment]
Hi saeed-NA, I have a few questions

* can you paste here the link giving the error to you
* what is the error that you are seeing?
* Which version are you installing?
* how are you installing it?

**Comment by angelrti** [comment]
Hello saeed-NA, can you provide the information above to help you with this issue?

Thanks,
Angel.

**Comment by angelrti** [comment]
Hi saeed-NA, I'm closing the issue because I don't have enough information to reproduce it (and haven't been able to reproduce it). Feel free to open it again to add more information about it.
